### PR TITLE
Switch tests and coverage to GitHub Action

### PR DESCRIPTION
**Pull request by rikhuijzer**
In https://github.com/JuliaCollections/Memoize.jl/pull/60, I noticed that the CI with Travis hangs on pending for quite a long time. This PR moves the CI over to a GitHub Action and is based on https://discourse.julialang.org/t/easy-workflow-file-for-setting-up-github-actions-ci-for-your-julia-package/49765.

### CODE REVIEW

**Comment by cstjean** [comment]
> continuous-integration/travis-ci

Is that an omission, or are we still testing some things on travis?

**Comment by rikhuijzer** [comment]
> > continuous-integration/travis-ci
> 
> Is that an omission, or are we still testing some things on travis?
```
I assumed it is due to Travis still checking the PR. Ripgrep shows that I should update the manual, but no other results for Travis.
$ rg travis
README.md
3:[![Build Status](https://travis-ci.org/JuliaCollections/Memoize.jl.png?branch=master)](https://travis-ci.org/JuliaCollections/Memoize.jl) [![Coverage Status](https://coveralls.io/repos/github/JuliaCollections/Memoize.jl/badge.svg?branch=master)](https://coveralls.io/github/JuliaCollections/Memoize.jl?branch=master)
```

**Comment by rikhuijzer** [comment]
It's something weird in the GitHub interface

> > continuous-integration/travis-ci
> 
> Is that an omission, or are we still testing some things on travis?

It's something weird in the GitHub interface, I think, because [here](https://github.com/JuliaCollections/Memoize.jl/pulls) the other pull request (https://github.com/JuliaCollections/Memoize.jl/pull/60) is still orange, while this PR is green.

**Comment by cstjean** [comment]
It's still `Required`, however. I guess I should go into the settings and take that out?

**Comment by rikhuijzer** [comment]
Good question, is there something in the settings? I recently also created https://github.com/GiovineItalia/Gadfly.jl/pull/1495 and there you can see that after the commit "Remove Travis", the Travis CI disappears. 

By the way, there is currently [degraded performance for GitHub Actions](https://www.githubstatus.com/).

**Comment by cstjean** [comment]
Also, I'm just a `Collaborator`, so maybe I can't change the list of required CI. @kmsquire Can you?

**Comment by cstjean** [comment]
@DilumAluthge Very sorry to bother you with this, but could you please go into `Settings` and take out the `continuous-integration/travis-ci` Required CI test?

I'm now de facto maintaining of this package, but as a collaborator, I can't access the settings.

**Comment by DilumAluthge** [comment]
I unfortunately do not have admin privileges on this repo.

@ararslan or @timholy Could you make @cstjean an admin on this repo?

**Comment by timholy** [comment]
Done.

**Comment by timholy** [comment]
Feel free to close #64. #65 still looks useful (it switches over to an event-based trigger for TagBot, xref https://discourse.julialang.org/t/ann-required-updates-to-tagbot-yml/49249).

**Comment by cstjean** [comment]
@rikhuijzer I just removed the required Travis checks, so we can merge this if conflicts are fixed. Or perhaps we should merge #64? Any opinion? I'm out of the loop with these changes.

**Comment by rikhuijzer** [comment]
When creating this PR, I ensured that I copied all the important parts 

> @rikhuijzer I just removed the required Travis checks, so we can merge this if conflicts are fixed. Or perhaps we should merge #64? Any opinion? I'm out of the loop with these changes.

The differences between this PR and the one from Tim Holy aren't too big. Mine updates the README too, and Tim's adds Windows whereas the original travis file was not testing on Windows. For my CV, I would appreciate if you merge my PR, but apart from that I don't think it makes much difference :stuck_out_tongue:

**Comment by rikhuijzer** [comment]
My CI file has 1.1 as the minimum version, but this should be 1.2. Unfortunately, I cannot change the files because I deleted my fork already. Either merge the PR and update it, or merge Tim's PR (and delete Windows).

**Comment by cstjean** [comment]
I'm shoulder-deep in the git voodoo swamp, but it [looks like](https://github.com/JuliaCollections/Memoize.jl/commits/master) this has been merged, in spite of what this PR's diff says. Please don't delete your fork again 🙂 

I guess we can close this? The commit log shows that the tests are failing, it's the only thing that worries me. Maybe we should open an empty PR to see what's up.

**Comment by cstjean** [comment]
Ok, looks like I fixed it. Thank you for this PR!

**Comment by rikhuijzer** [comment]
> I'm shoulder-deep in the git voodoo swamp

"git voodoo swamp" :rofl: 

> Please don't delete your fork again before the PR is merged :slightly_smiling_face:

Good tip :+1: 

> Ok, looks like I fixed it. Thank you for this PR!

You're welcome. Thank you for maintaining Memoize.jl

**Pull request closed without merging**
